/*
 * This file was generated by the Gradle 'init' task.
 */

java.sourceSets["main"].java {
  //  srcDir("src/main/antlr4")
    srcDir(tasks.generateGrammarSource)
}

sourceSets {
    main {
        java {
            // telling that output generateGrammarSource should be part of main source set
            // actuall passed value will be equal to `outputDirectory` that we configured above
           // srcDir(tasks.generateGrammarSource)
           //srcDir(tasks.generateGrammarSource)
           srcDir("target/generated-sources/antlr4/cz/vutbr/web/csskit/antlr4/")
        }
    }
}

plugins {
    `java-library`
    `maven-publish`
  //  `kotlin-dsl`
  
//  	kotlin("jvm") version "1.9.21"
   antlr
//    id("com.strumenta.antlr-kotlin") version "1.0.3"

//   application
   
   
   
}






//configurations {
//    compile {
//        extendsFrom = extendsFrom.findAll { it != configurations.antlr }
//    }
//}






repositories {
    mavenLocal()
    maven {
        url = uri("https://s01.oss.sonatype.org/content/repositories/snapshots/")
    }
    
    jcenter()

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    mavenCentral()
    maven{
    	url = uri("https://maven.clazzes.org/")
    }
    

}

dependencies {
    api(libs.org.slf4j.slf4j.api)
    
    implementation("org.htmlunit:neko-htmlunit:4.11.0")
    {
    	exclude(group = "xml-apis")
    }
    
    
    //implementation("org.antlr:antlr4:4.13.2")
    implementation("org.unbescape:unbescape:1.1.6.RELEASE")
    
    testImplementation(libs.junit.junit)
    
    
    antlr("org.antlr:antlr4:4.5")
    
    implementation("org.antlr:antlr4-maven-plugin:4.13.2")
    implementation("org.antlr:antlr4-runtime:4.13.2")
    

//    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))
//    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
//    implementation("com.google.guava:guava:30.1.1-jre")

//    testImplementation("org.jetbrains.kotlin:kotlin-test")
//    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")


//	implementation("org.apache.maven.plugins:maven-surefire-plugin:3.5.3")
}


//kotlin {
//    jvmToolchain(11)
//}


//application {
//    mainClass.set("sea.AppKt")
//}



//tasks {
//    generateGrammarSource {
//        arguments = arguments + listOf("-visitor")
//    }
//
//    compileKotlin {
//        dependsOn("generateGrammarSource")
//    }

//    compileTestKotlin {
//        dependsOn("generateTestGrammarSource")
//    }

//    jar {
//        manifest.attributes["Main-Class"] = application.mainClass

//        val dependencies = configurations
//            .runtimeClasspath
//            .get()
//            .map { zipTree(it) }

//        from(dependencies)
//        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
//    }
//}















group = "net.sf.cssbox"
version = "4.0.2-SNAPSHOT"
description = "jStyleParser"
java.sourceCompatibility = JavaVersion.VERSION_11

java {
    withSourcesJar()
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
