/*
 * This file was generated by the Gradle 'init' task.
 */

//java.sourceSets["main"].java {
  //  srcDir("src/main/antlr4")
//    srcDir(tasks.generateGrammarSource)
//}

sourceSets {
    main {
        java {
            // telling that output generateGrammarSource should be part of main source set
            // actuall passed value will be equal to `outputDirectory` that we configured above
           // srcDir(tasks.generateGrammarSource)
           //srcDir(tasks.generateGrammarSource)
         //  srcDir("target/generated-sources/antlr4/cz/vutbr/web/csskit/antlr4/")
         
         //srcDir("src/main/antlr4/cz/vutbr/web/csskit/antlr4/")
         
        // srcDir(tasks.generateGrammarSource)
         
       //  srcDir("src/main/antlr4/")
         
         srcDir("src/main/java/")
         
         srcDir("src/main/java/cz/vutbr/web/csskit/antlr4/")
        }
    }
    test {
            java {
            // telling that output generateGrammarSource should be part of main source set
            // actuall passed value will be equal to `outputDirectory` that we configured above
           // srcDir(tasks.generateGrammarSource)
           //srcDir(tasks.generateGrammarSource)
          // srcDir("target/generated-sources/antlr4/cz/vutbr/web/csskit/antlr4/")
          
         // srcDir(tasks.generateGrammarSource)
          
         // srcDir("src/main/antlr4/")
          
         // srcDir("src/main/java/")
         // srcDir("src/main/java/cz/vutbr/web/csskit/antlr4/")
        }
    }
}

plugins {
    `java-library`
    `maven-publish`
  //  `kotlin-dsl`
  
//  	kotlin("jvm") version "1.9.21"

//   antlr

//    id("com.strumenta.antlr-kotlin") version "1.0.3"

//   application
   
   
   
}


//tasks.withType<Test> {
//    useJUnitPlatform()
//}

//tasks.test {
//	useJUnitPlatform()
   // testLogging {
   // 	
     //   exceptionFormat = TestExceptionFormat.FULL
   // }
//}



//configurations {
//    compile {
//        extendsFrom = extendsFrom.findAll { it != configurations.antlr }
//    }
//}






repositories {
    mavenLocal()
    maven {
        url = uri("https://s01.oss.sonatype.org/content/repositories/snapshots/")
    }
    
    jcenter()

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    mavenCentral()
    maven{
    	url = uri("https://maven.clazzes.org/")
    }
    

}

dependencies {
    implementation (libs.org.slf4j.slf4j.api)
    
    
    implementation("org.jsoup:jsoup:1.20.1")
    
    
    
    implementation("org.apache.xerces:org.apache.xerces:2.12.2")
    
    implementation("org.htmlunit:neko-htmlunit:4.7.0")
 //   {
 //   	exclude(group = "xml-apis")
 //   }
    
    
  //  implementation("org.antlr:antlr4:4.13.2")
    implementation("org.unbescape:unbescape:1.1.6.RELEASE")
    
    implementation (libs.junit.junit)
    
  //  implementation("org.antlr:antlr4:4.13.2")
    
  //  antlr("org.antlr:antlr4:4.5")
    
 //   implementation("org.antlr:antlr4-maven-plugin:4.13.2")
    implementation("org.antlr:antlr4-runtime:4.13.2")
    

//    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))
//    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
//    implementation("com.google.guava:guava:30.1.1-jre")

//    testImplementation("org.jetbrains.kotlin:kotlin-test")
//    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")


//	implementation("org.apache.maven.plugins:maven-surefire-plugin:3.5.3")
}


//kotlin {
//    jvmToolchain(11)
//}


//application {
//    mainClass.set("sea.AppKt")
//}


tasks.withType<Jar> {
	duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

//tasks {
//	sourcesJar {
//   		duplicatesStrategy(DuplicatesStrategy.EXCLUDE)
//	}
//}


//tasks {
//    generateGrammarSource {
//        arguments = arguments + listOf("-visitor")
//    }
//
//    compileKotlin {
//        dependsOn("generateGrammarSource")
//    }

//    compileTestKotlin {
//        dependsOn("generateTestGrammarSource")
//    }

//    jar {
//        manifest.attributes["Main-Class"] = application.mainClass

//        val dependencies = configurations
//            .runtimeClasspath
//            .get()
//            .map { zipTree(it) }

//        from(dependencies)
//        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
//    }
//}


//tasks.generateGrammarSource {
//    maxHeapSize = "64m"
//    arguments = arguments + listOf("-visitor", "-long-messages")
//}












group = "net.sf.cssbox"
version = "4.0.2-SNAPSHOT"
description = "jStyleParser"
java.sourceCompatibility = JavaVersion.VERSION_11

java {
    withSourcesJar()
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
